package com.demo.entities;
// Generated Mar 11, 2024, 1:29:10 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account")
public class Account implements java.io.Serializable {

	private Integer id;
	private Role role;
	private String email;
	private String password;
	private String status;
	private String securityCode;
	private Set<Contact> contacts = new HashSet<Contact>(0);
	private Set<Reviews> reviewses = new HashSet<Reviews>(0);
	private Set<Menu> menus = new HashSet<Menu>(0);
	private Set<Branchs> branchses = new HashSet<Branchs>(0);
	private Set<User> users = new HashSet<User>(0);

	public Account() {
	}

	public Account(Role role, String email, String password, String status) {
		this.role = role;
		this.email = email;
		this.password = password;
		this.status = status;
	}

	public Account(Role role, String email, String password, String status, String securityCode, Set<Contact> contacts,
			Set<Reviews> reviewses, Set<Menu> menus, Set<Branchs> branchses, Set<User> users) {
		this.role = role;
		this.email = email;
		this.password = password;
		this.status = status;
		this.securityCode = securityCode;
		this.contacts = contacts;
		this.reviewses = reviewses;
		this.menus = menus;
		this.branchses = branchses;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "email", nullable = false, length = 250, unique=true)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "status", nullable = false, length = 250)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "security_code", length = 250)
	public String getSecurityCode() {
		return this.securityCode;
	}

	public void setSecurityCode(String securityCode) {
		this.securityCode = securityCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Contact> getContacts() {
		return this.contacts;
	}

	public void setContacts(Set<Contact> contacts) {
		this.contacts = contacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Reviews> getReviewses() {
		return this.reviewses;
	}

	public void setReviewses(Set<Reviews> reviewses) {
		this.reviewses = reviewses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Branchs> getBranchses() {
		return this.branchses;
	}

	public void setBranchses(Set<Branchs> branchses) {
		this.branchses = branchses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
