package com.demo.entities;
// Generated Mar 4, 2024, 11:56:23 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * CategoryFood generated by hbm2java
 */
@Entity
@Table(name = "category_food", catalog = "pento_sm4")
public class CategoryFood implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private String name;
	private int number;
	private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

	public CategoryFood() {
	}

	public CategoryFood(Menu menu, String name, int number) {
		this.menu = menu;
		this.name = name;
		this.number = number;
	}

	public CategoryFood(Menu menu, String name, int number, Set<OrderDetail> orderDetails) {
		this.menu = menu;
		this.name = name;
		this.number = number;
		this.orderDetails = orderDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id", nullable = false)
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoryFood")
	public Set<OrderDetail> getOrderDetails() {
		return this.orderDetails;
	}

	public void setOrderDetails(Set<OrderDetail> orderDetails) {
		this.orderDetails = orderDetails;
	}

}
