package com.demo.entities;
// Generated Feb 23, 2024, 1:06:06 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Images generated by hbm2java
 */
@Entity
@Table(name = "images")
public class Images implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Menu> menus = new HashSet<Menu>(0);

	public Images() {
	}

	public Images(String name) {
		this.name = name;
	}

	public Images(String name, Set<Menu> menus) {
		this.name = name;
		this.menus = menus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "images")
	public Set<Menu> getMenus() {
		return this.menus;
	}

	public void setMenus(Set<Menu> menus) {
		this.menus = menus;
	}

}
