package com.demo.entities;
// Generated Mar 15, 2024, 1:31:57 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail")
public class OrderDetail implements java.io.Serializable {

	private Integer id;
	private Menu menu;
	private Orders orders;
	private int quantity;
	private double price;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public OrderDetail() {
	}

	public OrderDetail(int quantity, double price) {
		this.quantity = quantity;
		this.price = price;
	}

	public OrderDetail(Menu menu, Orders orders, int quantity, double price, Set<Transaction> transactions) {
		this.menu = menu;
		this.orders = orders;
		this.quantity = quantity;
		this.price = price;
		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderDetail")
	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
